[terminal.shell]
args = ['--login']
program = "/usr/bin/fish"

[cursor]
style = "Beam"

[font]
size = 12.0

[font.normal]
family = "iosevka"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 6
y = 0

[colors.normal]
black = "#282828"  
red = "#fb4934" 
green = "#b8bb26" 
yellow = "#fabd2f" 
blue = "#83a598"  
magenta = "#d3869b" 
cyan = "#8ec07c" 
white = "#ebdbb2"  

[colors.primary]
background = "#1d2021" 
foreground = "#ebdbb2" 

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

