bar:
  height: 26
  location: bottom
  foreground: ffffffff
  background: 00000088

  font: Iosevka:pixelsize=15

  right:
    - mem:
        poll-interval: 2500
        content:
          string: {text: "mem:{used:mb}MB  "}
    - cpu:
        poll-interval: 2500
        content:
          map:
            conditions:
              id < 0:
                - string: {text: "cpu:"}
                - string: {text: "{cpu}%  "}
    - clock:
        content:
          - string: {text: "{date} ", right-margin: 5}
          - string: {text: "time:"}
          - string: {text: "{time} "}
  left:
    - dwl:
        number-of-tags: 5
        dwl-info-filename: "~/.cache/dwl_info"
        #name-of-tags: [ "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   "]
        name-of-tags: ["home  ", "dev  ", "mpv  ", "work  ", "web  "]
        content:
          list:
            items:
              - map:
                  conditions:
                    # default tag
                    id == 0: {string: {text: "{layout} {title}"}}

                    selected: {string: {text: "-> {name}"}}
                    ~empty: {string: {text: "{name}"}}
                    urgent: {string: {text: "=> {name} <="}}

